INSERT INTO ESTATE(city, postalcode, street, street_number, square_area) values ('Hamburg', '22527', 'Pinguniweg', '15', '25')
INSERT INTO ESTATE(city, postalcode, street, street_number, square_area) VALUES('Pescara', '5555', 'A.Volta', '22', '50')
INSERT INTO ESTATE_AGENT(name, address, login, password) VALUES('John', 'Somewhere', 'root', '$2a$10$uh23kSthoj8PsmzBbc6vqei9Dr/Cmkk1qDp72eUDTY/rlwXJqnWqO')
INSERT INTO ESTATE_AGENT(name, address, login, password) VALUES('John', 'Somewhere', 'user1', '$2a$10$CZziMjv953t0u83aGEnEy.u0fr9hJNLk8KDjVM.3GmBvoAp9sgYGO')
INSERT INTO HOUSE(floors, price, garden, estate_id) values ('3', '10000', 'yes', 1)
INSERT INTO APPARTMENT(floors, price, garden, rooms, balcony, builtinkitchen, estate_id) VALUES('3', '500000', 'Nope', '7', 1, 1, 2)
INSERT INTO MANAGES(estate_agent_id, estate_id) VALUES(1, 1)
INSERT INTO MANAGES(estate_agent_id, estate_id) VALUES(2, 2)
INSERT INTO PERSON(first_name, name, address) values('Looser', 'Sucker', 'somwhere nice')
INSERT INTO PERSON(first_name, name, address) values('Looser2', 'Sucker2', 'somwhere bad')
INSERT INTO CONTRACT(sign_date, place_id) VALUES('2018-04-04', 'Hamburg')
INSERT INTO CONTRACT(sign_date, place_id) VALUES('2016-04-04', 'Pescara')
INSERT INTO TENANCY_CONTRACT(start_date, duration, additional_costs, contract_id) values('2018-05-05', '12 months', 'Cleaning 1500', 1)
INSERT INTO PURCHASE_CONTRACT(installment, interest_rate, contract_id) values('12', '5%', 2)
INSERT INTO RENTS(tenancy_contract_id, appartment_id, person_id) VALUES(1, 1, 1)
INSERT INTO SELLS(house_id, person_id, purchase_contract_id) VALUES(1, 2, 1)
